version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vkfaces
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    command: python -m bot.main

    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app

  adminer:
    image: adminer:4.8.1
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  data:
